name: Release
run-name: CD - Validate and Create New Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release: Syntax - (*.*.*)'
        required: true
        type: string

# Ensures that only one job group runs at a time to avoid resource waste
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
  
jobs:
  create-release:
    name: Create New Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        run: npm ci

      - name: Retrieve current package version
        id: package-version
        run: |
          current_version=$(jq -r '.version' package.json)
          echo "Current version: $current_version"
          echo "::set-output name=current_version::$current_version"
      
      - name: Validate New Version
        id: validate-version
        run: node .github/scripts/comparePackageVersions.mjs ${{ steps.package-version.outputs.current_version }} ${{ github.event.inputs.version }}

      - name: Create Release
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const newVersion = core.getInput('version');
            const currentVersion = '${{ steps.package-version.outputs.current_version }}';

            try {
              await github.rest.repos.createRelease({
                owner,
                repo,
                tag_name: newVersion,
                name: `v${newVersion}`,
                body: `## Changes\n- New version: ${newVersion}\n- Previous version: ${currentVersion}`,
                draft: false,
                prerelease: false,
                generate_release_notes: false,
              });
            } catch (error) {
              core.setFailed(`Failed to create release: ${error.message}`);
            }

      - name: Update package.json file
        run: |
          jq --arg newVersion "${{ github.event.inputs.version }}" '.version = $newVersion' package.json > tmp.json && mv tmp.json package.json
      
      - name: Commit package.json file
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git checkout -b release-v${{ github.event.inputs.version }}
          git add package.json
          git commit -m "Update version to ${{ github.event.inputs.version }}"
        
      - name: Push changes to repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push --set-upstream origin release-v${{ github.event.inputs.version }}

      - name: Create Pull Request
        id: create-pull-request
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const newVersion = core.getInput('version');

            try {
              await github.rest.pulls.create({
                owner,
                repo,
                title: `Update version to ${newVersion}`,
                head: `release-v${newVersion}`,
                base: 'main',
              });
            } catch (error) {
              core.setFailed(`Failed to create pull request: ${error.message}`);
            }
